export const booksActions = {
  ADD_CHAPTER: 'ADD_CHAPTER',
  ADD_SUBSECTION: 'ADD_SUBSECTION',
  TOGGLE_SUBSECTION_READY: 'TOGGLE_SUBSECTION_READY',
  FETCH_BOOKS_REQUEST: 'FETCH_BOOKS_REQUEST',
  FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
  FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE'
}
